spring.application.name=logitrack

#Configuracion de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_db
spring.datasource.username=root
spring.datasource.password=123

#Cofiguración de JPA/Hibernate
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

