spring.application.name=logitrack

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/logitrack_db
spring.datasource.username=campus2023
spring.datasource.password=campus2023

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true